###> symfony/mercure-bundle ###
services:
    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':3000'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            ALLOW_ANONYMOUS: '1'
            CORS_ALLOWED_ORIGINS: '*'
            PUBLISH_ALLOWED_ORIGINS: '*'
        ports:
            - "3000:3000"
###< symfony/mercure-bundle ### 